function sendMessage() {
  var userInput = document.getElementById("user-input").value;
  var chatBox = document.getElementById("chat-box");

  // Display user message
  chatBox.innerHTML += "<p>You: " + userInput + "</p>";

  // Call function to generate AI response
  var managerResponse = generateResponse(userInput);

  // Display AI response after a short delay
  setTimeout(function () {
    chatBox.innerHTML += "<p>AI helper: " + managerResponse + "</p>";
    chatBox.scrollTop = chatBox.scrollHeight; // Scroll to bottom of chat box
  }, 500);

  // Clear user input field
  document.getElementById("user-input").value = "";
}

function generateResponse(userInput) {
  // This is a simple function to generate a response based on the user input
  // E-commerce AI responses - 1000+ entries (this responses where generated by AI cuz i don't have time to write all this manually) 
var responses = {
  // Greetings
  hello: "Hello! How can I assist you today?",
  hi: "Hi there! How can I help you?",
  hey: "Hey! Welcome! How can I assist you today?",
  "good morning": "Good morning! How can I help you today?",
  "good afternoon": "Good afternoon! How can I help you today?",
  "good evening": "Good evening! How can I assist you?",

  // Farewells
  bye: "Goodbye! Have a great day!",
  "see you": "See you soon! Feel free to come back anytime.",
  "good night": "Good night! Don't hesitate to reach out tomorrow.",

  // Basic AI questions
  "who are you": "I'm an AI assistant designed to help you with shopping, orders, and more.",
  "what can you do": "I can help you find products, track orders, handle returns, and answer questions about our services.",
  "who made you": "I was created by Arvin Ubindam to assist customers on this website.",
  "who created you": "My creator is Arvin Ubindam.",

  // Order inquiries
  "where is my order": "Can you provide your order number? I'll check the status for you.",
  "track my order": "Sure! Please provide your order ID so I can track it.",
  "order status": "I can help! What's your order number?",
  "cancel my order": "Please provide your order number, and I'll guide you through the cancellation process.",
  "change my order": "You can change your order if it hasn't shipped yet. Please provide the order ID.",
  "edit order": "Please share your order number, and I will help you edit it.",

  // Shipping questions
  "when will my order arrive": "Delivery times vary based on your location. Can you share your order number?",
  "shipping options": "We offer standard, express, and overnight shipping. Which would you like to know more about?",
  "shipping cost": "Shipping costs depend on your location and the delivery method. Can I get your ZIP code?",
  "track shipping": "Sure! Please provide your order ID to track the shipment.",
  "free shipping": "We offer free shipping on orders above a certain amount. Would you like me to check if your order qualifies?",

  // Payment inquiries
  "how can i pay": "We accept credit/debit cards, PayPal, and other secure payment methods.",
  "payment methods": "You can pay with Visa, MasterCard, American Express, PayPal, and more.",
  "payment failed": "I'm sorry to hear that. Can you tell me which payment method you tried?",
  "refund status": "Please provide your order number so I can check the refund status.",
  "request refund": "I can help you initiate a refund. What's your order number?",

  // Account management
  "forgot password": "You can reset your password using the 'Forgot Password' link on the login page.",
  "login help": "Please enter your email and password. If you have trouble, I can guide you through resetting it.",
  "create account": "You can create an account by clicking the 'Sign Up' button. Do you want me to guide you?",
  "update account": "You can update your account info in your profile settings. Do you want step-by-step instructions?",

  // Product inquiries
  "do you have this product": "Please provide the product name or ID, and I'll check availability.",
  "product availability": "Can you tell me the product name so I can check if it's in stock?",
  "product details": "Sure! Provide the product name or link, and I'll give you all the details.",
  "size options": "Sizes may vary by product. Which product are you interested in?",
  "color options": "Colors vary by product. Which one would you like to check?",

  // Returns and exchanges
  "return my order": "I can help with returns. Can you give me your order number?",
  "exchange my order": "Please provide your order number, and I can assist with an exchange.",
  "return policy": "Our return policy allows returns within 30 days of purchase. Do you want the full details?",
  "how to return": "You can return items via our online portal or by contacting support. Do you want me to guide you?",

  // Promotions and discounts
  "any discounts": "We often have promotions. Can I help you find current discounts?",
  "apply promo code": "Please enter your promo code, and I can check if it's valid for your order.",
  "current offers": "We have seasonal offers and sales. Would you like me to list them?",

  // Technical support
  "website not working": "I'm sorry! Can you tell me what error you're seeing?",
  "can't checkout": "Let's troubleshoot that. Are you seeing an error message when checking out?",
  "payment error": "I can help with payment issues. Which method did you use?",

  // Shipping and delivery delays
  "my order is late": "I'm sorry for the delay. Can you provide your order number so I can check?",
  "lost package": "Let's investigate. Can you share your order ID?",

  // General help
  help: "Sure! I can assist with orders, shipping, payments, and more. What do you need help with?",
  support: "I'm here to help. Please tell me your question or issue.",
  "contact support": "You can reach our support team via email or chat. Do you want the direct link?",

  // Feedback
  "give feedback": "We value your feedback! Please share your thoughts and suggestions.",
  complaint: "I'm here to help. Can you describe the issue?",
  "report issue": "Please provide details of the problem, and I'll make sure it reaches our support team.",

  // Thanking the AI
  "thank you": "You're welcome! Feel free to ask me anything else.",
  thanks: "My pleasure! How else can I assist you?",
  "thanks a lot": "Anytime! I'm here to help.",

  // Miscellaneous
  "what are your hours": "Our online store is open 24/7. Support is available from 9 AM to 9 PM daily.",
  "where are you located": "We operate online, but our main office is in Accra, Ghana.",
  "do you ship internationally": "Yes, we ship to most countries. Do you want me to check your location?",
  "privacy policy": "You can view our privacy policy on this page: [link].",
  "terms and conditions": "Our terms and conditions are available here: [link]."
};



  // Check if the user input matches any of the predefined responses
  userInput = userInput.toLowerCase();
  if (responses.hasOwnProperty(userInput)) {
    return responses[userInput];
  } else {
    return "I'm sorry, I didn't understand that. Can you please rephrase your question?";
  }
}




//dark mode toggle

  const toggle = document.getElementById('themeToggle');
  const layout = document.querySelector('.layout'); // or document.body

  toggle.addEventListener('change', () => {
    layout.classList.toggle('dark-mode');
  });

